import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/nasiko-api",
    },
    {
      type: "category",
      label: "Health",
      items: [
        {
          type: "doc",
          id: "api/healthcheck-api-v-1-healthcheck-get",
          label: "Health Check",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Agent Registry",
      items: [
        {
          type: "doc",
          id: "api/create-registry-api-v-1-registry-post",
          label: "Create Agent in the Registry",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-my-agents-api-v-1-registry-user-agents-get",
          label: "Get My Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-my-agents-info-api-v-1-registry-user-agents-info-get",
          label: "Get info of all agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-registry-by-name-api-v-1-registry-agent-name-agent-name-get",
          label: "Get Registry by Name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-registry-by-agent-id-api-v-1-registry-agent-id-agent-id-get",
          label: "Get Registry by Agent ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upsert-registry-by-name-api-v-1-registry-agent-agent-name-put",
          label: "Upsert Agent in the Registry by Name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-agent-completely-api-v-1-registry-agent-agent-id-delete",
          label: "Delete Agent and All Resources",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/update-agent-version-status-api-v-1-registry-agent-agent-name-version-status-put",
          label: "Update Agent Version Status",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Agent Upload",
      items: [
        {
          type: "doc",
          id: "api/upload-agent-zip-api-v-1-agents-upload-post",
          label: "Upload Agent Zip",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-agent-directory-api-v-1-agents-upload-directory-post",
          label: "Upload Agent Directory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-upload-status-by-agent-latest-api-v-1-upload-status-agent-agent-name-latest-put",
          label: "Update Latest Upload Status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-user-upload-agents-api-v-1-user-upload-agents-get",
          label: "Get My Upload Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/download-agent-files-api-v-1-agents-agent-name-download-get",
          label: "Download Agent Files",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Agent Operations",
      items: [
        {
          type: "doc",
          id: "api/create-build-record-api-v-1-agents-build-post",
          label: "Create Build Record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/create-deployment-record-api-v-1-agents-deploy-post",
          label: "Create Deployment Record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-build-status-api-v-1-agents-build-build-id-status-put",
          label: "Update Build Status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-deployment-status-api-v-1-agents-deployment-deployment-id-status-put",
          label: "Update Deployment Status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-version-mapping-api-v-1-agents-build-version-mapping-get",
          label: "Get Version Mapping",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Agent Updates",
      items: [
        {
          type: "doc",
          id: "api/update-agent-api-v-1-agents-agent-id-update-put",
          label: "Update Agent",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/rollback-agent-api-v-1-agents-agent-id-rollback-post",
          label: "Rollback Agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-version-history-api-v-1-agents-agent-id-versions-get",
          label: "Get Version History",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "GitHub",
      items: [
        {
          type: "doc",
          id: "api/github-login-api-v-1-auth-github-login-get",
          label: "GitHub Login",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/github-callback-api-v-1-auth-github-callback-get",
          label: "GitHub OAuth Callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-github-token-api-v-1-auth-github-token-get",
          label: "Get GitHub Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/github-logout-api-v-1-auth-github-logout-post",
          label: "GitHub Logout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-github-repositories-api-v-1-github-repositories-get",
          label: "List GitHub Repositories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/clone-github-repository-api-v-1-github-clone-post",
          label: "Clone GitHub Repository",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/github-user-login-api-v-1-auth-github-login-user-get",
          label: "GitHub User Login",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "N8N Operations",
      items: [
        {
          type: "doc",
          id: "api/register-n-8-n-workflow-api-v-1-agents-n-8-n-register-post",
          label: "Register N8N Workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/save-user-n-8-n-credentials-api-v-1-agents-n-8-n-connect-post",
          label: "Save User N8N Credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-user-n-8-n-credentials-api-v-1-agents-n-8-n-credentials-get",
          label: "Get User N8N Credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-user-n-8-n-credentials-api-v-1-agents-n-8-n-credentials-put",
          label: "Update User N8N Credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-user-n-8-n-credentials-api-v-1-agents-n-8-n-credentials-delete",
          label: "Delete User N8N Credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-workflows-api-v-1-agents-n-8-n-workflows-get",
          label: "List N8N Workflows",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Super User Management",
      items: [
        {
          type: "doc",
          id: "api/register-user-api-v-1-user-register-post",
          label: "Register New User",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Search",
      items: [
        {
          type: "doc",
          id: "api/search-users-api-v-1-search-users-get",
          label: "Search Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/search-agents-api-v-1-search-agents-get",
          label: "Search Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/index-user-api-v-1-search-index-user-post",
          label: "Index User",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "chat_history",
      items: [
        {
          type: "doc",
          id: "api/create-session-api-v-1-chat-session-post",
          label: "Create new session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-session-api-v-1-chat-session-session-id-delete",
          label: "Delete Session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-chat-history-api-v-1-chat-session-session-id-get",
          label: "Get chat history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-session-history-api-v-1-chat-session-list-get",
          label: "Get paginated session history",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "observability",
      items: [
        {
          type: "doc",
          id: "api/get-all-sessions-api-v-1-observability-session-list-get",
          label: "Get All Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-session-details-api-v-1-observability-session-session-id-get",
          label: "Get Session Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-trace-details-api-v-1-observability-trace-project-id-trace-id-get",
          label: "Get Trace Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-span-details-api-v-1-observability-span-span-id-get",
          label: "Get Span Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agent-project-stats-api-v-1-observability-agent-agent-id-stats-get",
          label: "Get Agent Project Stats",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "NANDA Registry",
      items: [
        {
          type: "doc",
          id: "api/nanda-health-check-api-v-1-nanda-health-get",
          label: "NANDA API Health Check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-agents-api-v-1-nanda-agents-get",
          label: "Get All Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agent-by-id-api-v-1-nanda-agents-agent-id-get",
          label: "Get Agent by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/search-agents-api-v-1-nanda-agents-search-get",
          label: "Search Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agents-by-category-api-v-1-nanda-agents-category-category-get",
          label: "Get Agents by Category",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-online-agents-api-v-1-nanda-agents-online-get",
          label: "Get Online Agents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agent-facts-api-v-1-nanda-agents-agent-id-facts-get",
          label: "Get Agent Facts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-agent-statistics-api-v-1-nanda-statistics-get",
          label: "Get Agent Statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-all-messages-api-v-1-nanda-messages-get",
          label: "Get All Messages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-messages-by-agent-api-v-1-nanda-messages-agent-agent-id-get",
          label: "Get Messages by Agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-messages-by-conversation-api-v-1-nanda-messages-conversation-conversation-id-get",
          label: "Get Messages by Conversation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-messages-by-type-api-v-1-nanda-messages-type-message-type-get",
          label: "Get Messages by Type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-message-statistics-api-v-1-nanda-messages-statistics-get",
          label: "Get Message Statistics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/agentbuildindb",
          label: "AgentBuildInDB",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentbuildstatusupdaterequest",
          label: "AgentBuildStatusUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentdeploymentbase",
          label: "AgentDeploymentBase",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentdeploymentstatusupdaterequest",
          label: "AgentDeploymentStatusUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentdirectoryuploadrequest",
          label: "AgentDirectoryUploadRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentrollbackrequest",
          label: "AgentRollbackRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentrollbackresponse",
          label: "AgentRollbackResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentsearchresponse",
          label: "AgentSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentsearchresult",
          label: "AgentSearchResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentupdateresponse",
          label: "AgentUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentuploaditemresponse",
          label: "AgentUploadItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentuploadresponse",
          label: "AgentUploadResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentversionhistoryresponse",
          label: "AgentVersionHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/agentversioninfo",
          label: "AgentVersionInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/body-update-agent-api-v-1-agents-agent-id-update-put",
          label: "Body_update_agent_api_v1_agents__agent_id__update_put",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/body-upload-agent-zip-api-v-1-agents-upload-post",
          label: "Body_upload_agent_zip_api_v1_agents_upload_post",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/buildstatus",
          label: "BuildStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/capabilities",
          label: "Capabilities",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/chathistory",
          label: "ChatHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/chathistoryresponse",
          label: "ChatHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createsessionrequest",
          label: "CreateSessionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/deploymentstatus",
          label: "DeploymentStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/githubclonerequest",
          label: "GithubCloneRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/githubrepository",
          label: "GithubRepository",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/githubrepositorylistresponse",
          label: "GithubRepositoryListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/httpvalidationerror",
          label: "HTTPValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/messageresponse",
          label: "MessageResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/n-8-nregisterrequest",
          label: "N8nRegisterRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/n-8-nregisterresponse",
          label: "N8nRegisterResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/nandaapiresponse",
          label: "NANDAApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/paginationmetadata",
          label: "PaginationMetaData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/provider",
          label: "Provider",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/registrycreaterequest",
          label: "RegistryCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/registryitemdetailresponse",
          label: "RegistryItemDetailResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/registrysingleresponse",
          label: "RegistrySingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/registryupsertrequest",
          label: "RegistryUpsertRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessiondata",
          label: "SessionData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessionhistory",
          label: "SessionHistory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessionhistoryresponse",
          label: "SessionHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/sessionresponse",
          label: "SessionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/simpleuseragentresponse",
          label: "SimpleUserAgentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/simpleuseragentsresponse",
          label: "SimpleUserAgentsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/simpleuseruploadagentresponse",
          label: "SimpleUserUploadAgentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/simpleuseruploadagentsresponse",
          label: "SimpleUserUploadAgentsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/skill",
          label: "Skill",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/successresponse",
          label: "SuccessResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploadinforesponse",
          label: "UploadInfoResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploadstatusitemresponse",
          label: "UploadStatusItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploadstatussingleresponse",
          label: "UploadStatusSingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploadstatusupdaterequest",
          label: "UploadStatusUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/useragentitemresponse",
          label: "UserAgentItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/useragentsresponse",
          label: "UserAgentsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usern-8-nconnectresponse",
          label: "UserN8NConnectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usern-8-ncredentialcreaterequest",
          label: "UserN8NCredentialCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usern-8-ncredentialresponse",
          label: "UserN8NCredentialResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usern-8-ncredentialsingleresponse",
          label: "UserN8NCredentialSingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usern-8-ncredentialupdaterequest",
          label: "UserN8NCredentialUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/userregistrationrequest",
          label: "UserRegistrationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/userregistrationresponse",
          label: "UserRegistrationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usersearchresponse",
          label: "UserSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/usersearchresult",
          label: "UserSearchResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/versionmappingresponse",
          label: "VersionMappingResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/versionstatusupdaterequest",
          label: "VersionStatusUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/versionstatusupdateresponse",
          label: "VersionStatusUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/workflowlistresponse",
          label: "WorkflowListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/workflowsummary",
          label: "WorkflowSummary",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
